# Generated by Django 2.1.5 on 2020-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
