# Generated by Django 2.1.5 on 2020-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200223_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
