# Generated by Django 2.1.5 on 2020-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
