# Generated by Django 2.1.5 on 2020-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200220_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
