# Generated by Django 2.1.5 on 2020-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200220_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
